source/Cadastre/Models/DatabaseSurveyRequest.cs
namespace Cadastre.Models
{
	public class DatabaseSurveyRequest
	{
		public string Server { get; set; }

		public string Database { get; set; }

		public bool IsReference { get; set; }
	}
}

source/Cadastre/Models/SurveyRequest.cs
using System.Collections.Generic;

namespace Cadastre.Models
{
	public class SurveyRequest
	{
		public string Name { get; set; }

		public IEnumerable<DatabaseSurveyRequest> Databases { get; set; }
	}
}

source/Cadastre/Models/SurveyViewModel.cs
using System;

namespace Cadastre.Models
{
	public class SurveyViewModel
	{
		public int Id { get; set; }
		public string Name { get; set; }
		public string User { get; set; }
		public string Machine { get; set; }
		public DateTime Start { get; set; }
		public DateTime? End { get; set; }
	}
}

source/Cadastre/Controllers/Api/DatabaseSurveysController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Http;

using SchemaSurveyor.Core.Surveys;

namespace Cadastre.Controllers.Api
{
	public class DatabaseSurveysController : ApiController
	{
		private readonly ISurveyRepository _surveyRepository;

		public DatabaseSurveysController(ISurveyRepository surveyRepository)
		{
			_surveyRepository = surveyRepository;
		}

		[HttpGet]
		[Route("api/Surveys/{surveyId:int}/Databases", Name = "DatabaseSurveysApi")]
		public IEnumerable<DatabaseSurvey> Get(int surveyId)
		{
			var result = _surveyRepository.GetDatabaseSurveys(surveyId);

			return result;
		}

		[HttpGet]
		[Route("api/Surveys/{surveyId:int}/Databases/{databaseSurveyId:int}", Name = "DatabaseSurveyApi")]
		public DatabaseSurvey Get(int surveyId, int databaseSurveyId)
		{
			var result = _surveyRepository
				.GetDatabaseSurveys(surveyId)
				.SingleOrDefault(x => x.Id == databaseSurveyId);

			return result;
		}
	}
}

source/Cadastre/Controllers/Api/ExtraObjectsController.cs
using System.Linq;
using System.Web.Http;

using SchemaSurveyor.Core;
using SchemaSurveyor.Core.ExtraObjects;

namespace Cadastre.Controllers.Api
{
	public class ExtraObjectsController : ApiController
	{
		private readonly IExtraObjectRepository _extraObjectRepository;

		public ExtraObjectsController(IExtraObjectRepository extraObjectRepository)
		{
			_extraObjectRepository = extraObjectRepository;
		}

		[HttpGet]
		[Route("api/Surveys/{surveyId:int}/Databases/{databaseSurveyId:int}/ExtraObjects", Name = "ExtraObjectsApi")]
		public ExtraObjectCollection Get(int surveyId, int databaseSurveyId)
		{
			var result = _extraObjectRepository.GetExtraObjects(surveyId, databaseSurveyId);

			return result;
		}

		[HttpGet]
		[Route("api/Surveys/{surveyId:int}/Databases/{databaseSurveyId:int}/ExtraObjects/{objectType:alpha}", Name = "ExtraObjectTypeApi")]
		public IQueryable<ExtraObject> Get(int surveyId, int databaseSurveyId, string objectType)
		{
			var type = Enums.Parse<ObjectType>(objectType);

			var result = _extraObjectRepository.GetExtraObjects(surveyId, databaseSurveyId, type);

			return result;
		}
	}
}

source/Cadastre/Controllers/Api/MissingObjectsController.cs
using System.Linq;
using System.Web.Http;

using SchemaSurveyor.Core;
using SchemaSurveyor.Core.MissingObjects;

namespace Cadastre.Controllers.Api
{
	public class MissingObjectsController : ApiController
	{
		private readonly IMissingObjectRepository _missingObjectRepository;

		public MissingObjectsController(IMissingObjectRepository missingObjectRepository)
		{
			_missingObjectRepository = missingObjectRepository;
		}

		[HttpGet]
		[Route("api/Surveys/{surveyId:int}/Databases/{databaseSurveyId:int}/MissingObjects", Name = "MissingObjectsApi")]
		public MissingObjectCollection Get(int surveyId, int databaseSurveyId)
		{
			var result = _missingObjectRepository.GetMissingObjects(surveyId, databaseSurveyId);

			return result;
		}

		[HttpGet]
		[Route("api/Surveys/{surveyId:int}/Databases/{databaseSurveyId:int}/MissingObjects/{objectType:alpha}", Name = "MissingObjectTypeApi")]
		public IQueryable<MissingObject> Get(int surveyId, int databaseSurveyId, string objectType)
		{
			var type = Enums.Parse<ObjectType>(objectType);

			var result = _missingObjectRepository.GetMissingObjects(surveyId, databaseSurveyId, type);

			return result;
		}
	}
}

source/Cadastre/Controllers/Api/ServersController.cs
using System.Collections.Generic;
using System.Web.Http;

using SchemaSurveyor.Core.Servers;

namespace Cadastre.Controllers.Api
{
	public class ServersController : ApiController
	{
		private readonly IServerRepository _serverRepository;
		private readonly IDatabaseRepository _databaseRepository;

		public ServersController(IServerRepository serverRepository, IDatabaseRepository databaseRepository)
		{
			_serverRepository = serverRepository;
			_databaseRepository = databaseRepository;
		}

		[HttpGet]
		[Route("api/Servers", Name = "ServersApi")]
		public IEnumerable<string> Get()
		{
			var result = _serverRepository.GetServers();

			return result;
		}

		[HttpGet]
		[Route("api/Servers/{serverName}/Databases", Name = "DatabasesApi")]
		public IEnumerable<string> Get(string serverName)
		{
			var result = _databaseRepository.GetDatabases(serverName);

			return result;
		}
	}
}

source/Cadastre/Controllers/Api/SurveysController.cs
using System.Linq;
using System.Web.Http;

using Cadastre.Models;
using Cadastre.Surveys;

using SchemaSurveyor.Core.Surveys;

namespace Cadastre.Controllers.Api
{
	public class SurveysController : ApiController
	{
		private readonly ISurveyRepository _surveyRepository;
		private readonly ISurveyExecutor _surveyExecutor;

		public SurveysController(ISurveyRepository surveyRepository, ISurveyExecutor surveyExecutor)
		{
			_surveyRepository = surveyRepository;
			_surveyExecutor = surveyExecutor;
		}

		[HttpGet]
		[Route("api/Surveys", Name = "SurveysApi")]
		public IQueryable<Survey> Get()
		{
			var result = _surveyRepository.Get();

			return result;
		}

		[HttpGet]
		[Route("api/Surveys/{surveyId:int}", Name = "SurveyApi")]
		public Survey Get(int surveyId)
		{
			var result = _surveyRepository.Get(surveyId);

			return result;
		}

		[HttpPost]
		[Route("api/Surveys", Name = "AddSurveyApi")]
		public bool Post(SurveyRequest request)
		{
			var result = _surveyExecutor.Execute(request.Name, request.Databases);

			return result;
		}
	}
}

source/Cadastre/Controllers/SurveysController.cs
using System.Web.Mvc;

using Cadastre.Models;

using SchemaSurveyor.Core.Surveys;

namespace Cadastre.Controllers
{
	public class SurveysController : Controller
	{
		private readonly ISurveyRepository _surveyRepository;

		public SurveysController(ISurveyRepository surveyRepository)
		{
			_surveyRepository = surveyRepository;
		}

		[HttpGet]
		[ActionName("Index")]
		public ActionResult Index()
		{
			return View();
		}

		[HttpGet]
		[ActionName("Survey")]
		public ActionResult Survey(int surveyId)
		{
			var survey = _surveyRepository.Get(surveyId);

			var model = new SurveyViewModel
			{
				Id = survey.Id,
				Name = survey.Name,
				Machine = survey.Machine,
				User = survey.User,
				Start = survey.Start,
				End = survey.End
			};

			return View(model);
		}

		[HttpGet]
		[ActionName("Create")]
		public ActionResult Create()
		{
			return View();
		}
	}
}

source/Cadastre/Views/Shared/_Layout.cshtml
@using Cadastre

<!DOCTYPE html>

<html lang="en">
	<head>
		<meta charset="utf-8" />
		<title>@ViewBag.Title</title>
		<link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		@Styles.Render("~/bundles/css")
		@Scripts.Render("~/bundles/modernizr")
	</head>
	<body>
		<header class="container">
			<nav class="navbar navbar-default" role="navigation">
				<div class="navbar-header">
					@Html.ActionLink("cadastre", "Index", "Surveys", null, new { @class = "navbar-brand" })
				</div>
				<div class="collapse navbar-collapse">
					<ul class="nav navbar-nav navbar-right">
						@Html.BuildNavListItem("Surveys", "Index", "Surveys")
						@Html.BuildNavListItem("Create", "Create", "Surveys")
					</ul>
				</div>
			</nav>
		</header>
		<div id="body" class="container">
			<section>
				@RenderBody()
			</section>
		</div>

		@Scripts.Render("~/bundles/jquery")
		@Scripts.Render("~/bundles/bootstrap")
		@Scripts.Render("~/bundles/knockout")
		@Scripts.Render("~/bundles/cadastre")
		@RenderSection("scripts", required: false)
	</body>
</html>

source/Cadastre/Views/Surveys/Create.cshtml
@using Cadastre

@{
	ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Request", "Surveys", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
	<div id="create-survey">
		<div class="form-group">
			<label for="name" class="col-md-2 control-label">Name: </label>
			<div class="col-md-10">
				<input id="name" class="form-control" name="Name" type="text" data-bind="value: name" placeholder="Survey name..." />
			</div>
		</div>
		<div class="form-group">
			<label for="server" class="col-md-2 control-label">Server: </label>
			<div class="col-md-10">
				<select id="server" class="form-control" name="Server" data-bind="options: availableServers, value: server"></select>
			</div>
		</div>
		<div class="form-group">
			<label for="database" class="col-md-2 control-label">Database: </label>
			<div class="col-md-10">
				<select id="database" class="form-control" name="Database" multiple data-bind="optionsText: 'database', options: availableDatabases, selectedOptions: selectedDatabases"></select>
			</div>
		</div>

		@Html.Button("Add", new Dictionary<string, object> { { "id", "add-database" }, { "data-bind", "click: addSelectedDatabase" }, { "class", "btn btn-default pull-right" } })

		<table id="server-list" class="table table-striped">
			<thead>
				<tr>
					<th>Server</th>
					<th>Database</th>
					<th>Reference Schema</th>
					<th></th>
				</tr>
			</thead>
			<tbody data-bind="foreach: databases">
				<tr>
					<td data-bind="text: server"></td>
					<td data-bind="text: database"></td>
					<td><input type="radio" name="ReferenceDatabase" data-bind="value: id, checked: $parent.referenceDatabase" /></td>
					<td class="text-center"><a href="#" data-bind="click: $parent.removeSelectedDatabase">remove</a></td>
				</tr>
			</tbody>
		</table>

		<button id="submit-survey" type="submit" class="btn btn-default" data-bind="click: create">Create</button>
	</div>
}

@section scripts {
<script type="text/javascript">
	$(document).ready(function () {
		cadastre.create.init('@Url.HttpRouteUrl("ServersApi", null)', '@Url.HttpRouteUrl("AddSurveyApi", null)', '#create-survey');
	});
</script>
}

source/Cadastre/Views/Surveys/Index.cshtml
@{
	ViewBag.Title = "Surveys";
}

<h2>Surveys</h2>

<table id="surveys" class="table table-striped table-hover">
	<thead>
		<tr>
			<th>Survey</th>
			<th>Host</th>
			<th>User</th>
			<th>Start</th>
			<th>End</th>
		</tr>
	</thead>
	<tbody data-bind="foreach: surveys">
		<tr data-bind="click: $parent.showSurvey" class="cursor-hand">
			<td data-bind="text: name"></td>
			<td data-bind="text: machine"></td>
			<td data-bind="text: user"></td>
			<td data-bind="text: start"></td>
			<td data-bind="text: end"></td>
		</tr>
	</tbody>
</table>

@section scripts {
<script type="text/javascript">
	$(document).ready(function () {
		cadastre.surveys.init('@Url.HttpRouteUrl("SurveysApi", null)', '@Url.Action("Survey", "Surveys", new { surveyId = 0 })', '#surveys');
	});
</script>
}

source/Cadastre/Views/Surveys/Survey.cshtml
@using Cadastre.Models

@model SurveyViewModel

@{
	ViewBag.Title = String.Format("Survey: {0}", @Model.Name);
}

<h2>@Model.Name</h2>

<section id="survey">
	<dl class="dl-horizontal">
		<dt>User:</dt>
		<dd>@Model.User</dd>
		<dt>Machine:</dt>
		<dd>@Model.Machine</dd>
		<dt>Start:</dt>
		<dd>@Model.Start</dd>
		@if (@Model.End.HasValue)
		{
			<dt>End:</dt>
			<dd>@Model.End</dd>
		}
	</dl>
	<h3>Databases:</h3>
	<table class="table">
		<thead>
			<tr>
				<th>Server</th>
				<th>Database</th>
				<th>Reference</th>
				<th>Connection Error</th>
				<th>ETL Error</th>
				<th>Duration</th>
			</tr>
		</thead>
		<tbody data-bind="foreach: { data: databases, as: 'database' }">
			<tr data-bind="css: { 'cursor-hand': isReferenceSchema() === false }, click: toggleDetails">
				<td data-bind="text: server"></td>
				<td data-bind="text: database"></td>
				<td class="text-center"><input type="checkbox" disabled="disabled" data-bind="checked: isReferenceSchema" /></td>
				<td class="text-center"><input type="checkbox" disabled="disabled" data-bind="checked: hadConnectionError" /></td>
				<td class="text-center"><input type="checkbox" disabled="disabled" data-bind="checked: hadEtlError" /></td>
				<td><span data-bind="text: duration">0</span> ms</td>
			</tr>
			<tr data-bind="visible: areDetailsVisible">
				<td colspan="6">
					<div class="survey-results">
						<ul class="nav nav-tabs" data-bind="foreach: { data: tabs, as: 'tab' }">
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown"><span data-bind="text: title"></span> <span class="caret"></span></a>
								<ul class="dropdown-menu" data-bind="foreach: { data: types, as: 'type' }">
									<li data-bind="css: { disabled: isDisabled }"><a data-bind="text: title, attr: { href: '#db-' + database.id() + '-' + tab.id() + '-' + type.id() }" data-toggle="tab"></a></li>
								</ul>
							</li>
						</ul>
						<div class="tab-content" data-bind="foreach: { data: tabs, as: 'tab' }">
							<!-- ko foreach: { data: types, as: 'type' } -->
							<div class="tab-pane db-object-list" data-bind="attr: { id: 'db-' + database.id() + '-' + tab.id() + '-' + type.id() }">
								<!-- ko if: needsParentColumn -->
								<table class="table table-condensed">
									<thead>
										<tr>
											<th>Table</th>
											<th>Name</th>
										</tr>
									</thead>
									<tbody data-bind="foreach: objects">
										<tr>
											<td data-bind="text: parent"></td>
											<td data-bind="text: name"></td>
										</tr>
									</tbody>
								</table>
								<!-- /ko -->
								<!-- ko ifnot: needsParentColumn -->
								<table class="table table-condensed">
									<thead>
										<tr>
											<th>Name</th>
										</tr>
									</thead>
									<tbody data-bind="foreach: objects">
										<tr>
											<td data-bind="text: name"></td>
										</tr>
									</tbody>
								</table>
								<!-- /ko -->
							</div>
							<!-- /ko -->
						</div>
					</div>
				</td>
			</tr>
		</tbody>
	</table>
</section>

@section scripts {
<script type="text/javascript">
	$(document).ready(function () {
		var urls = {
			Missing: '@Url.HttpRouteUrl("MissingObjectsApi", new { surveyId = @Model.Id, databaseSurveyId = 0 })',
			Extra: '@Url.HttpRouteUrl("ExtraObjectsApi", new { surveyId = @Model.Id, databaseSurveyId = 0 })'
		};

		cadastre.survey.init(urls, '@Url.HttpRouteUrl("DatabaseSurveysApi", new { surveyId = @Model.Id })', '#survey');
	});
</script>
}